# Generated by Django 4.2 on 2023-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_scannedbarcode_delete_barcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=255, unique=True)),
                ("make", models.CharField(blank=True, max_length=255, null=True)),
                ("storage", models.CharField(blank=True, max_length=255, null=True)),
                ("cpu", models.CharField(blank=True, max_length=255, null=True)),
                ("ram", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ScannedBarcode",
        ),
    ]
