# Generated by Django 4.2 on 2023-04-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_computers_delete_inventoryitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computers",
            name="docking_station",
            field=models.BooleanField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="computers",
            name="monitors",
            field=models.BooleanField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="computers",
            name="printer",
            field=models.BooleanField(blank=True, max_length=3, null=True),
        ),
    ]
