# Generated by Django 4.2 on 2023-05-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_computers_docking_station_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computers",
            name="computer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="computers",
            name="service_tag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
