# Generated by Django 4.2 on 2023-05-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_computers_computer_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="printers",
            fields=[
                (
                    "service_tag",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("make", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="computers",
            old_name="monitors",
            new_name="monitor",
        ),
        migrations.CreateModel(
            name="monitors",
            fields=[
                (
                    "asset_tag",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "service_tag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("make", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "computer",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.computers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="docking_stations",
            fields=[
                (
                    "asset_tag",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "service_tag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("make", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "computer",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.computers",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="computers",
            name="printers",
            field=models.ManyToManyField(
                blank=True, related_name="Computers", to="inventory.printers"
            ),
        ),
    ]
