# Generated by Django 4.2 on 2023-05-04 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0010_printers_rename_monitors_computers_monitor_monitors_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="docking_stations",
            name="computer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.computers",
            ),
        ),
        migrations.AlterField(
            model_name="monitors",
            name="computer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitors",
                to="inventory.computers",
            ),
        ),
    ]
