# Generated by Django 4.2 on 2023-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_computers_id_docking_stations_id_monitors_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computers",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="docking_stations",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="monitors",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
