# Generated by Django 4.2 on 2023-05-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_alter_computers_asset_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitors",
            name="computer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monitors",
                to="inventory.computers",
            ),
        ),
    ]
