# Generated by Django 4.2 on 2023-05-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_monitors_computer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computers",
            name="printers",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="Computers", to="inventory.printers"
            ),
        ),
    ]
