# Generated by Django 4.2 on 2023-05-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_alter_computers_printers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="computers",
            options={"verbose_name": "Computer", "verbose_name_plural": "Computers"},
        ),
        migrations.AlterModelOptions(
            name="docking_stations",
            options={
                "verbose_name": "Docking Station",
                "verbose_name_plural": "Docking Stations",
            },
        ),
        migrations.AlterModelOptions(
            name="monitors",
            options={"verbose_name": "Monitor", "verbose_name_plural": "Monitors"},
        ),
        migrations.AlterModelOptions(
            name="printers",
            options={"verbose_name": "Printer", "verbose_name_plural": "Printers"},
        ),
        migrations.RemoveField(
            model_name="computers",
            name="docking_station",
        ),
        migrations.RemoveField(
            model_name="computers",
            name="monitor",
        ),
        migrations.RemoveField(
            model_name="computers",
            name="printer",
        ),
    ]
