# Generated by Django 4.2 on 2023-05-10 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_computers_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="docking_stations",
            options={
                "verbose_name": "DockingStation",
                "verbose_name_plural": "DockingStations",
            },
        ),
    ]
