# Generated by Django 4.2 on 2023-05-10 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_docking_stations_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="docking_stations",
            options={
                "verbose_name": "Docking Station",
                "verbose_name_plural": "Docking Stations",
            },
        ),
        migrations.AlterField(
            model_name="docking_stations",
            name="computer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="docking_stations",
                to="inventory.computers",
            ),
        ),
    ]
