# Generated by Django 4.2 on 2023-05-10 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_alter_docking_stations_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docking_stations",
            name="computer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.computers",
            ),
        ),
    ]
