# Generated by Django 4.2 on 2023-05-10 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_alter_docking_stations_computer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docking_stations",
            name="computer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="docking_stations",
                to="inventory.computers",
            ),
        ),
    ]
